name: Run Crypto Predictor

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run main pipeline
      - name: Run pipeline
        run: |
          python pipeline.py || echo "pipeline.py failed but continuing..."

      # Run backtest
      - name: Run backtest
        run: |
          python backtest.py || echo "backtest.py failed but continuing..."

      # Ensure accuracy_reports folder exists
      - name: Ensure accuracy_reports folder exists
        run: mkdir -p accuracy_reports

      # Commit and push timestamped reports to main branch
      - name: Push accuracy reports to main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          TIMESTAMP=$(date +'%H-%M-%S_%d-%m-%Y')
          REPORT_NAME="${TIMESTAMP}_accuracy_report.json"
          
          # Move the newly generated report to accuracy_reports folder with timestamp
          mv accuracy_reports/*.json accuracy_reports/$REPORT_NAME
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add accuracy_reports/$REPORT_NAME
          git commit -m "Add accuracy report $TIMESTAMP" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git main