name: Run Crypto Predictor

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          echo "Running pipeline.py..."
          python pipeline.py || echo "pipeline.py failed but continuing..."

      - name: Run backtest
        run: |
          echo "Running backtest.py..."
          python backtest.py || echo "backtest.py failed but continuing..."

      - name: Ensure accuracy_reports folder exists
        run: |
          mkdir -p accuracy_reports
          echo "accuracy_reports folder is ready."

      - name: List accuracy reports
        run: |
          echo "Listing accuracy_reports folder contents..."
          ls -lh accuracy_reports/ || echo "Folder is empty"

      - name: Commit and push accuracy reports
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout main
          git add accuracy_reports/
          git commit -m "Add new accuracy report from GitHub Actions" || echo "No changes to commit"

          # Push using the GH_PAT secret
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main

      - name: Upload accuracy reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: accuracy_reports
          path: accuracy_reports/